## Importing libraries


In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

## Importing CSV File

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data = data.drop(['RowNumber','CustomerId','Surname'] , axis = 1)

## Transforming the data into Vectors From Text

In [3]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

## Using Ohe Hot Encoding

#### Why One-Hot Encoding Might Not Work Before Splitting
If you apply One-Hot Encoding before separating dependent and independent variables, it can cause issues if:

1. You're trying to encode the entire DataFrame (including the target column)

2. If your target (dependent variable) is categorical and accidentally gets encoded along with features, you might mess up your y values.

In [4]:
## Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [5]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [6]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [8]:
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

## Saving the Encoders and Scalar

In [9]:
import pickle

## Save the encoders and sscaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)


## Spliting the data into dependent variable and indepedent variable

In [10]:
X = data.drop('Exited', axis=1)
y = data['Exited']

## Spliting the Data into Training and Test set


In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state= 42)

In [12]:
X_train

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9254          686       1   32       6       0.00              2          1   
1561          632       1   42       4  119624.60              2          1   
1670          559       1   24       3  114739.92              1          1   
6087          561       0   27       9  135637.00              1          1   
6669          517       1   56       9  142147.32              1          0   
...           ...     ...  ...     ...        ...            ...        ...   
5734          768       1   54       8   69712.74              1          1   
5191          682       0   58       1       0.00              1          1   
5390          735       0   38       1       0.00              3          0   
860           667       1   43       8  190227.46              1          1   
7270          697       1   51       1  147910.30              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
9254               1        179093.26               1.0                0.0   
1561               1        195978.86               0.0                1.0   
1670               0         85891.02               0.0                0.0   
6087               0        153080.40               1.0                0.0   
6669               0         39488.04               1.0                0.0   
...              ...              ...               ...                ...   
5734               1         69381.05               1.0                0.0   
5191               1           706.50               1.0                0.0   
5390               0         92220.12               1.0                0.0   
860                0         97508.04               1.0                0.0   
7270               1         53581.14               0.0                1.0   

      Geography_Spain  
9254              0.0  
1561              0.0  
1670              1.0  
6087              0.0  
6669              0.0  
...               ...  
5734              0.0  
5191              0.0  
5390              0.0  
860               0.0  
7270              0.0  

[8000 rows x 12 columns]

In [13]:
X_train.shape

(8000, 12)

In [14]:
X_test

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
6252          596       1   32       3   96709.07              2          0   
4684          623       1   43       1       0.00              2          1   
1731          601       0   44       4       0.00              2          1   
4742          506       1   59       8  119152.10              2          1   
4521          560       0   27       7  124995.98              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
6412          602       0   53       5   98268.84              1          0   
8285          609       1   25      10       0.00              1          0   
7853          730       0   47       7       0.00              1          1   
1095          692       1   29       4       0.00              1          1   
6929          628       1   39       1  115341.19              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
6252               0         41788.37               0.0                1.0   
4684               1        146379.30               1.0                0.0   
1731               0         58561.31               0.0                0.0   
4742               1        170679.74               0.0                1.0   
4521               1        114669.79               0.0                0.0   
...              ...              ...               ...                ...   
6412               1         45038.29               0.0                1.0   
8285               1        109895.16               1.0                0.0   
7853               0         33373.26               1.0                0.0   
1095               0         76755.99               1.0                0.0   
6929               1        107674.30               0.0                1.0   

      Geography_Spain  
6252              0.0  
4684              0.0  
1731              1.0  
4742              0.0  
4521              1.0  
...               ...  
6412              0.0  
8285              0.0  
7853              0.0  
1095              0.0  
6929              0.0  

[2000 rows x 12 columns]

In [15]:
X_test.shape

(2000, 12)

In [16]:
# Detect non-numeric columns
print(X_train.dtypes)

CreditScore            int64
Gender                 int64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Geography_France     float64
Geography_Germany    float64
Geography_Spain      float64
dtype: object


## Importing Feature scaling

In [17]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [19]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [20]:
import pickle

with open('scaler.csv', 'wb') as file:
    pickle.dump(scaler, file)

In [21]:
data

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1               1.0   
1                  1        112542.58       0               0.0   
2                  0        113931.57       1               1.0   
3                  0         93826.63       0               1.0   
4                  1         79084.10       0               0.0   
...              ...              ...     ...               ...   
9995               0         96270.64       0               1.0   
9996               1        101699.77       0               1.0   
9997               1         42085.58       1               1.0   
9998               0         92888.52       1               0.0   
9999               0         38190.78       0               1.0   

      Geography_Germany  Geography_Spain  
0                   0.0              0.0  
1                   0.0              1.0  
2                   0.0              0.0  
3                   0.0              0.0  
4                   0.0              1.0  
...                 ...              ...  
9995                0.0              0.0  
9996                0.0              0.0  
9997                0.0              0.0  
9998                1.0              0.0  
9999                0.0              0.0  

[10000 rows x 13 columns]

##  TensorFlow in ANN


In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

## Making Neural Network (Input Layer , Hidden Layer , Output Layer)

In [24]:
model =  Sequential([
    Dense(64 , activation='relu' , input_shape=(X_train.shape[1],)),         ## Hidden Layer 1 -- connected with input layer
    Dense(32 , activation='relu' ),    ## Hidden Layer 2 -- connected with hidden layer 1
    Dense(1 , activation='relu')       ## Output Layer 
])

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

<LossFunctionWrapper(<function binary_crossentropy at 0x136083740>, kwargs={'from_logits': False, 'label_smoothing': 0.0, 'axis': -1})>

In [27]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

## TensorBoard

In [28]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

## Seting up Early Stopping 

In [29]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=9,restore_best_weights=True)

## Train the model


In [30]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7594 - loss: 1.5055 - val_accuracy: 0.7775 - val_loss: 1.7497
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.8158 - loss: 2.0147 - val_accuracy: 0.7895 - val_loss: 1.7011
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.7688 - loss: 2.4833 - val_accuracy: 0.7560 - val_loss: 3.5476
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7756 - loss: 3.2424 - val_accuracy: 0.8135 - val_loss: 2.4864
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.8088 - loss: 2.4411 - val_accuracy: 0.8275 - val_loss: 1.5271
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.8148 - loss: 1.7311 - val_accuracy: 0.8235 - val_loss: 1.0404
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.8150 - loss: 1.2006 - val_accuracy: 0.8260 - val_loss: 0.5598
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.8294 - loss: 0.5

In [31]:
model.save('model.h5')

## Time to Load Tensorboard Extension

In [32]:
%load_ext tensorboard

In [46]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6008 (pid 12287), started 0:00:01 ago. (Use '!kill 12287' to kill it.)

## How to Load the File in Code

In [34]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [35]:
### Load the trained model, scaler pickle,onehot
model=load_model('model.h5')

## load the encoder and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

## lets find the probabily of percentage of fail

In [36]:
## Example 

input_data = {
    'CreditScore' : 600 ,
	'Geography'	: 'France' ,
    'Gender' : 'Male' ,
	'Age' : '40',
    'Tenure': 3 ,
    'Balance': 60000 ,	
    'NumOfProducts'	: 2 ,
    'HasCrCard'	: 1 ,
    'IsActiveMember' : 1, 
    'EstimatedSalary' : 50000    
}

In [37]:
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df


/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [38]:
input_df=pd.DataFrame([input_data])
input_df

CreditScore Geography Gender Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male  40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [39]:
## Encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

CreditScore Geography  Gender Age  Tenure  Balance  NumOfProducts  \
0          600    France       1  40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

## combining onehot encoding data with input data

In [40]:
## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

CreditScore  Gender Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1  40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

## Scaling the Data

In [41]:
## Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


array([[ 1.19900285e+03,  1.72572313e+00,  9.18768279e+01,
        -6.73149059e+00,  1.20493359e+05, -3.50795899e+00,
        -1.38944225e+00, -1.21845455e+00,  8.62535496e+04,
         6.49202671e-01, -1.02583358e+00, -1.74616572e+00]])

## Predicting The Result 

In [42]:
## PRedict churn
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array([[0.06466417]], dtype=float32)

## Prediction Probability

In [43]:
prediction_proba = prediction[0][0]

In [44]:
prediction_proba

0.06466417

In [45]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.
